package com.mesakii.cityinfoJava.Controller;

import com.mesakii.cityinfoJava.Entity.City;
import com.mesakii.cityinfoJava.Repository.RepositoryCity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Created by tiejin on 8/8/2018.
 */

@Controller //This means that this class is a Controller
@RequestMapping(path="/city") // This means URL's start with /demo (after Application path)
public class CityController {
    @Autowired// This means to get the bean called userRepository
              // Which is auto-generated by Spring, we will use it to handle the data
    private RepositoryCity repositoryCity;

    @GetMapping(path="get")
    public @ResponseBody Iterable<City> getAllCitys(){
        return repositoryCity.findAll();
    }

}
